#ifndef INC_LFW_CONFIG_H__
#define INC_LFW_CONFIG_H__
/**
@file Config.h
@author t-sakai
@date 2016/05/08 create
*/
namespace lfw
{
#define LFW_INPUT_DIRECT_INPUT
#define LFW_CONFIG_SHADOW_MAXCASCADES (4)
#define LFW_CONFIG_NAMESIZE (32)
#define LFW_CONFIG_NAMELENGTH (LFW_CONFIG_NAMESIZE-1)
#define LFW_CONFIG_FILENAMESIZE (64)
#define LFW_CONFIG_FILENAMELENGTH (LFW_CONFIG_FILENAMESIZE-1)
}
#endif //INC_LFW_CONFIG_H__
