"struct VS_OUTPUT\n"
"{\n"
"    float4 position : POSITION0;\n"
"#ifdef PNORMAL\n"
"    float3 normal : TEXCOORD0;\n"
"#endif\n"
"#ifdef PCOLOR\n"
"    float4 color : COLOR0;\n"
"#endif\n"
"#ifdef PTEX0\n"
"    float4 tex0 : TEXCOORD1;\n"
"#endif\n"
"#ifdef PPOS\n"
"    float3 pos0 : TEXCOORD2;\n"
"#endif\n"
"#ifdef LIGHTVS\n"
"    float4 specular0 : TEXCOORD3;\n"
"#ifdef TEXSHADE\n"
"    float2 tex2 : TEXCOORD4;\n"
"#endif\n"
"#endif //LIGHTVS\n"
"};\n"
"static const float c_fzero = 0.0;\n"
"static const float c_fone = 1.0;\n"
"static const float PI = 3.14159265358979323846;\n"
"static const float PI2 = 6.28318530717958647692;\n"
"static const float INV_PI = 0.31830988618379067153;\n"
"static const float INV_PI2 = 0.15915494309189533576;\n"
"#ifdef LIGHTVS\n"
"uniform float3 ambient;\n"
"uniform float4 dlColor;\n"
"uniform float4 diffuse;\n"
"uniform float3 emissive;\n"
"#else //LIGHTVS\n"
"uniform float3 dlDir;\n"
"uniform float4 dlColor;\n"
"uniform float3 camPos;\n"
"uniform float4 diffuse;\n"
"uniform float3 ambient;\n"
"uniform float3 emissive;\n"
"#endif //LIGHTVS\n"
"#ifdef PNORMAL\n"
"uniform float4 specular;\n"
"#endif\n"
"//繝・け繧ｹ繝√Ε\n"
"#if defined(PTEX0)\n"
"sampler texAlbedo;\n"
"#endif\n"
"#ifdef FRESNEL\n"
"static const float c_ffive = 5.0;\n"
"static const float c_fresnel0 = 0.0397436;\n"
"static const float c_fresnel1 = 0.0856832;\n"
"uniform float4 specular;\n"
"uniform float fresnel;\n"
"// calculate fresnel term for diffuse and specular\n"
"void calc_fresnel(out float fd, out float fs, float F, float eh, float nl)\n"
"{\n"
"  float F2 = c_fone - F;\n"
"  fs = F + F2*pow((c_fone - eh), c_ffive);\n"
"  fd = F + F2*pow((c_fone - nl), c_ffive);\n"
"}\n"
"#endif\n"
"float4 main(VS_OUTPUT input) : COLOR\n"
"{\n"
"    // 濶ｲ險育ｮ・\n"
"    //-------------\n"
"    float4 color;\n"
"#ifdef TEXALBEDO\n"
"    //繝・ぅ繝輔Η繝ｼ繧ｺ繝・け繧ｹ繝√Ε蜿ら・\n"
"    color = tex2D(texAlbedo, input.tex0.xy);\n"
"#else\n"
"    color = diffuse;\n"
"#endif\n"
"#ifdef PCOLOR\n"
"    color.xyz *= input.color;\n"
"#endif\n"
"#ifdef FRESNEL\n"
"    //F0: vertical reflectance\n"
"    //N: normal, L:light vector, E: eye ector, H: normalize(L+E)\n"
"    //Fd(F0) = F0 + (1-F0)(1-NL)^5   Fs(F0) = F0 + (1-F0)*(1-EH)^5\n"
"    //approximation (shininess+2)/(4*pi*(2-2^*(-shininess/2)) = (shininess+2.04)/8*pi = 0.0397436 * shininess + 0.0856832\n"
"    //Rd*(1.0/pi)*(1.0 - Rs*Fd(F0))*(NL) + Rs * (shininess+2)/(4*pi*(2-2^(-shininess/2)) * Fs(F0) * NH^shininess\n"
"    float3 L = dlDir;\n"
"    float3 N = normalize(input.normal);\n"
"    float3 E = normalize(camPos - input.pos0); //隕也ｷ壹・繧ｯ繝医Ν\n"
"    float3 H = normalize(L+E); //繝上・繝輔・繧ｯ繝医Ν\n"
"    float cosNL = max(c_fzero, dot(N,L));\n"
"    float cosEH = max(c_fzero, dot(E,H));\n"
"    float cosNH = max(c_fzero, dot(N,H));\n"
"    float fd, fs;\n"
"    calc_fresnel(fd, fs, fresnel, cosEH, cosNL);\n"
"    float shininess = specular.w;\n"
"    float rs = (c_fresnel0 * shininess + c_fresnel1) * fs * pow(cosNH, shininess);\n"
"    float3 rd = (float3(c_fone, c_fone, c_fone) - specular.xyz*fd) * INV_PI;\n"
"    color.xyz = (color.xyz * rd * cosNL + specular.xyz * rs) * dlColor.xyz + ambient * rd;\n"
"#endif\n"
"#ifdef LIGHTVS\n"
"    color.xyz = (color.xyz * input.specular0.w + input.specular0.xyz) * dlColor.xyz + ambient * color.xyz;\n"
"#elif defined(PNORMAL)\n"
"    vec3 L = dlDir;\n"
"    vec3 N = normalize(input.normal);\n"
"    vec3 E = normalize(camPos - v_pos0);\n"
"    vec3 H = normalize(L+E);\n"
"    float cosNH = max(c_fzero, dot(N,H));\n"
"    float shininess = specular.w;\n"
"    float rs = pow(cosNH, shininess);\n"
"    color.xyz = (color.xyz * cosNH + specular.xyz * rs) * dlColor.xyz + ambient * color.xyz;\n"
"#else\n"
"    color.xyz *= (dlColor.xyz + ambient);\n"
"#endif\n"
"#ifdef EMISSIVE\n"
"    color.xyz += emissive;\n"
"#endif\n"
"    return color;\n"
"}\n"
