"struct VS_OUTPUT\n"
"{\n"
"    float4 position : POSITION0;\n"
"#ifdef PNORMAL\n"
"    float3 normal : TEXCOORD1;\n"
"#endif\n"
"#ifdef PCOLOR\n"
"    float3 color : COLOR0;\n"
"#endif\n"
"#ifdef PTEX0\n"
"    float2 tex0 : TEXCOORD0;\n"
"#endif\n"
"#ifdef PPOS\n"
"    float3 pos0 : TEXCOORD2;\n"
"#endif\n"
"};\n"
"static const float PI = 3.14159265358979323846;\n"
"static const float PI2 = 6.28318530717958647692;\n"
"static const float INV_PI = 0.31830988618379067153;\n"
"static const float INV_PI2 = 0.15915494309189533576;\n"
"#ifdef FRESNEL\n"
"//繝・ぅ繝輔Η繝ｼ繧ｺ繝輔Ξ繝阪Ν繝ｪ繝輔Ξ繧ｯ繧ｿ繝ｳ繧ｹ縺ｮ霑台ｼｼ蠑丈ｿよ焚\n"
"static const float4 coeffFdr = float4(-1.440f, 0.710f, 0.668f, 0.0636f);\n"
"uniform float3 dlDir;\n"
"uniform float3 camPos;\n"
"uniform float4 specular;\n"
"#endif\n"
"//繝槭ユ繝ｪ繧｢繝ｫ險ｭ螳・\n"
"uniform float4 diffuse;\n"
"//繝・け繧ｹ繝√Ε\n"
"#if defined(PTEX0)\n"
"sampler texAlbedo;\n"
"#endif\n"
"float4 main(VS_OUTPUT input) : COLOR\n"
"{\n"
"    // 濶ｲ險育ｮ・\n"
"    //-------------\n"
"    float4 color;\n"
"#if defined(PTEX0)\n"
"    //繝・ぅ繝輔Η繝ｼ繧ｺ繝・け繧ｹ繝√Ε蜿ら・\n"
"    color = tex2D(texAlbedo, input.tex0);\n"
"#else\n"
"    color = diffuse;\n"
"#endif\n"
"#if defined(FRESNEL)\n"
"    float3 L = dlDir;\n"
"    float3 N = normalize(input.normal);\n"
"    float3 V = normalize(camPos - input.pos0); //隕也ｷ壹・繧ｯ繝医Ν\n"
"    float3 H = normalize(L+V); //繝上・繝輔・繧ｯ繝医Ν\n"
"    float cosNL = max(0.0f, dot(N,L));\n"
"    float cosVH = max(0.0f, dot(V,H));\n"
"    float cosNH = max(0.0f, dot(N,H));\n"
"    const float shininess = specular.w;\n"
"    const float3 ks = specular.xyz;\n"
"    //Phong\n"
"    float3 reflectance = ks * (shininess + 2)*INV_PI2*pow(max(0.0001f, cosNH), shininess);\n"
"    //繝輔Ξ繝阪Ν 隍・ｴ螻域釜繝ｻ蛛丞・縺ｪ縺・\n"
"    float ni = 1.5f; //隍・ｴ螻域釜邇・ｮ滄Κ\n"
"    //const float nt = 1.0;\n"
"    float F0 = (1.0f - ni)/(1.0f + ni);\n"
"    F0 = F0*F0;\n"
"    //繝輔Ξ繝阪Ν繝ｪ繝輔Ξ繧ｯ繧ｿ繝ｳ繧ｹ\n"
"    float Fr = F0 + (1.0f - F0)* pow(1.0f - cosNL, 5.0f);\n"
"    //蜿榊ｰ・・蜑ｲ蜷・\n"
"    reflectance *= Fr;\n"
"    //繝・ぅ繝輔Η繝ｼ繧ｺ繝輔Ξ繝阪Ν繝ｪ繝輔Ξ繧ｯ繧ｿ繝ｳ繧ｹ\n"
"    //蜈･蟆・ｧ偵→豕慕ｷ壹・菴吝ｼｦﾎｸ縲∝・蟆・・繧ｯ繝医Νﾏ峨∝ｱ域釜邇・・豈釆ｷ縺ｫ縺､縺・※縲・\n"
"    //繝・ぅ繝輔Η繝ｼ繧ｺ繝ｪ繝輔Ξ繧ｯ繧ｿ繝ｳ繧ｹ Fdr = 竏ｫﾎｩ(Fr(ﾎｷ,ﾎｸ))dﾏ・\n"
"    //霑台ｼｼ縲：dr = -1.440/(ﾎｷ*ﾎｷ) + 0.710/ﾎｷ + 0.668 + 0.0636*ﾎｷ\n"
"    //float invNi = 1.0f/ni;\n"
"    //float4 reflectPoly = float4(invNi*invNi, invNi, 1.0f, ni);\n"
"    //float Fdr = dot(reflectPoly, coeffFdr);\n"
"    float Fdr = 1.0f - reflectance;\n"
"    //諡｡謨｣蜿榊ｰ・・蜑ｲ蜷・\n"
"    float4 dcolor;\n"
"    dcolor.xyz = diffuse * Fdr * INV_PI;\n"
"    dcolor.w = diffuse.w;\n"
"    color.xyzw = dcolor;\n"
"    color.xyz += reflectance;\n"
"#else\n"
"#endif\n"
"#if defined(PCOLOR)\n"
"    color.xyz *= input.color;\n"
"#endif\n"
"    return color;\n"
"}\n"
